config/routes.rb
Rails.application.routes.draw do
  resources :subjects
  resources :categories
  devise_for :users
  resources :books
  root "books#home"
  get 'search', to: "books#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :subject
end

app/models/category.rb
class Category < ApplicationRecord
  # has_many :books
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :books
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  def home
    @books = Book.all
  end

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  #search bar
  def search
    @books = Book.where("subject_id LIKE ?", "%" + params[:q] + "%")
    @books = Book.where("title LIKE ?", "%" + params[:q] + "%")
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :subject_id, :author, :publish_date, :price, :description, :image)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:Name)
    end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: %i[ show edit update destroy ]

  # GET /subjects or /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1 or /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects or /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to subject_url(@subject), notice: "Subject was successfully created." }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1 or /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to subject_url(@subject), notice: "Subject was successfully updated." }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1 or /subjects/1.json
  def destroy
    @subject.destroy

    respond_to do |format|
      format.html { redirect_to subjects_url, notice: "Subject was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subject_params
      params.require(:subject).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="control-group">
    <%= form.label :subject_id %>
    <%= collection_select(:book, :subject_id, Subject.all, :id, :name, {}, {:multiple => false})%>
  </div>

  <div class="form-group">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="form-group">
    <%= form.label :publish_date %>
    <%= form.date_select :publish_date %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

<!--start of  picture form -->
  <div class="form-group">
    <%if book.image.attached? %>
    <%= image_tag book.image, style: "width: 200px; display: block" %>
    <%end %>

    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control" %>
  </div>
<!--End of  picture form -->

  <div class="form-group">
    <%= form.submit controller.action_name.capitalize + "Book", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/books/_header.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home Page', root_path, class: "navbar-brand" %>
        </li>

        <li class="nav-item">
          <%= link_to 'All Subjects', subjects_path , class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'All Books', books_path , class: "nav-link" %>
        </li>





    <%if user_signed_in? %>

        <li class="nav-item">
          <%= link_to 'Add Subject', new_subject_path , class: "nav-link" %>
        </li>

        <li class="nav-item">
        <%= link_to 'Add Book', new_book_path , class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete , class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Edit Profile', edit_user_registration_path , class: "nav-link" %>
        </li>

    <%else %>
          <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path , class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path , class: "nav-link" %>
          </li>

    <%end %>


      </ul>

          <form class="d-flex" role="search" action="/search">
            <input class="form-control me-2" name="q" type="text" placeholder="Search by name" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>

          </form>

    </div>
  </div>
</nav>

app/views/books/_searchResult.html.erb
<p id="notice"><%= notice %></p>

<h1>All Books</h1>


<!--Book Subjecties drop down menu-->



<table class="table table-striped">
  <thead>
  <tr>
    <th>Image</th>
    <th>Title</th>
    <th>Subject</th>
    <th>Author</th>
    <th>Publish date</th>
    <th>Price</th>
    <th>Description</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>

  <% @books.each do |book| %>
    <tr>
      <%if book.image.attached? %>
        <td><%= image_tag book.image, style: "width: 100px; display: block" %></td>
      <%else %>
        <td><%= 'No Image'%></td>
      <%end %>
      <td><%= book.title %></td>
      <td><%= book.subject.name %></td>
      <td><%= book.author %></td>
      <td><%= book.publish_date %></td>
      <td><%= book.price %></td>
      <td><%= book.description %></td>
      <td><%= link_to 'Show', book %></td>
      <td><%= link_to 'Edit', edit_book_path(book) %></td>
      <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>

  <% end %>

  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/home.html.erb
<p id="notice"><%= notice %></p>

<h1>Home page</h1>
<h4> our 3 latest books</h4>


<!--Book subjects drop down menu-->

<table class="table table-striped">
  <thead>
  <tr>
    <th>Image</th>
    <th>Title</th>
    <th>Subject</th>
    <th>Author</th>
    <th>Publish date</th>
    <th>Price</th>
    <th>Description</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <!--Sort the books by date from newest to  oldest-->
  <% @books =  @books.order("publish_date DESC") %>
  <% @books.each do |book| %>
    <tr>
      <%if book.image.attached? %>
        <td><%= image_tag book.image, style: "width: 100px; display: block" %></td>
      <%else %>
        <td><%= 'No Image'%></td>
      <%end %>
      <td><%= book.title %></td>
      <td><%= book.subject.name %></td>
      <td><%= book.author %></td>
      <td><%= book.publish_date %></td>
      <td><%= book.price %></td>
      <td><%= book.description %></td>
      <td><%= link_to 'Show', book %></td>
      <td><%= link_to 'Edit', edit_book_path(book) %></td>
      <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <!--Shows only last 3 books-->
    <%break if book == @books[2] %>
  <% end %>

  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Books</h1>


<!--Book Subjecties drop down menu-->



<table class="table table-striped">
  <thead>
    <tr>
      <th>Image</th>
      <th>Title</th>
      <th>Subject</th>
      <th>Author</th>
      <th>Publish date</th>
      <th>Price</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @books.each do |book| %>
      <tr>
        <%if book.image.attached? %>
          <td><%= image_tag book.image, style: "width: 100px; display: block" %></td>
        <%else %>
          <td><%= 'No Image'%></td>
        <%end %>
        <td><%= book.title %></td>
        <td><%= book.subject.name %></td>
        <td><%= book.author %></td>
        <td><%= book.publish_date %></td>
        <td><%= book.price %></td>
        <td><%= book.description %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

    <% end %>

  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/search.html.erb
<h1> Search Results</h1>

<%= render  "books/searchResult" %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Subject ID:</strong>
  <%= @book.subject_id %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @book.subject.name%>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Publish date:</strong>
  <%= @book.publish_date %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>Image:</strong>
  <%if @book.image.attached? %>
    <%= image_tag @book.image, style: "width: 200px; display: block" %>
  <%end %>

</p>




<%= link_to 'Edit', edit_book_path(@book), class: "btn btn-secondary" %> |
<%= link_to 'Back', books_path %>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Name %>
    <%= form.text_field :Name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.Name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.Name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @category.id %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<!--Linking  to Bootstrap-->
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
    <title>Home Page</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "books/header" %>
    <div class = "container"
      <%= yield %>
    </div>
  </body>
</html>

app/views/subjects/_form.html.erb
<%= form_with(model: subject) do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
        <% subject.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subjects</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.id %></td>
        <td><%= subject.name %></td>
        <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject', new_subject_path %>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subject.name %>
</p>

<p>
  <strong>ID:</strong>
  <%= @subject.id %>
</p>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>